//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRoks.Sitecore.Analyzers.Design.LogExceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheRoks.Sitecore.Analyzers.Design.LogExceptions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use exception type catch block..
        /// </summary>
        internal static string NoCatchBlockDescription {
            get {
                return ResourceManager.GetString("NoCatchBlockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use exception type catch block..
        /// </summary>
        internal static string NoCatchBlockMessageFormat {
            get {
                return ResourceManager.GetString("NoCatchBlockMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use exception type catch block..
        /// </summary>
        internal static string NoCatchBlockTitle {
            get {
                return ResourceManager.GetString("NoCatchBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log error on exceptions..
        /// </summary>
        internal static string NoErrorLogDescription {
            get {
                return ResourceManager.GetString("NoErrorLogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log error on exceptions..
        /// </summary>
        internal static string NoErrorLogMessageFormat {
            get {
                return ResourceManager.GetString("NoErrorLogMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log error on exceptions..
        /// </summary>
        internal static string NoErrorLogTitle {
            get {
                return ResourceManager.GetString("NoErrorLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include exception as parameter on log error.
        /// </summary>
        internal static string NoExceptionOnErrorLogDescription {
            get {
                return ResourceManager.GetString("NoExceptionOnErrorLogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include exception as parameter on log error.
        /// </summary>
        internal static string NoExceptionOnErrorLogMessageFormat {
            get {
                return ResourceManager.GetString("NoExceptionOnErrorLogMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include exception as parameter on log error.
        /// </summary>
        internal static string NoExceptionOnErrorLogTitle {
            get {
                return ResourceManager.GetString("NoExceptionOnErrorLogTitle", resourceCulture);
            }
        }
    }
}
